spring:
  application:
    name: eureka-client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        heartbeat:
          enabled: true
server:
  port: 2001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/